name: Validate with HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration" 